### ISSUE TITLE
【会員】新規登録画面か-電話番号がない

### ISSUE THREAD

**Issue by stogashi146** [konpirasou/nagano-cake#8]
## 問題の内容
会員側の新規登録画面にて、住所の下が
郵便番号になっている

## 再現手順
会員側のヘッダーから、新規登録ボタンを押して
新規登録画面を表示する。

## 修正すべき内容
郵便番号（ハイフンなし）から、
電話番号（ハイフンなし）に修正お願いします。

![image](https://user-images.githubusercontent.com/83628316/125893150-8efd5489-94fc-411e-b3fa-461b63453db4.png)

**Comment by maruyu31** [comment]
修正しました！
